---
- hosts: dpub_front
  user: da-dev
  sudo: yes
  tasks:
  - name: download MySQL5.7 repository
    get_url:
      url=https://dev.mysql.com/get/mysql-apt-config_0.8.6-1_all.deb
      dest=/tmp/mysql-apt-config_0.8.6-1_all.deb
  - name: install deb
    apt: deb=/tmp/mysql-apt-config_0.8.6-1_all.deb
  - name: delete deb
    file: path=/tmp/mysql-apt-config_0.8.6-1_all.deb state=absent
  - name: MySQL | install mysql packages
    apt: name={{ item }} force=yes  state=latest update_cache=yes
    with_items:
      - mysql-client
      - mysql-common
      - mysql-server
      - libmysqlclient-dev
# python-mysqldb and python-selinux are not for python3      
#      - python-mysqldb
#      - python-selinux
  - name: MySQL | restart mysql
    service: name=mysql state=restarted
