---
- hosts: dpub_front
  user: da-dev
  sudo: yes
  vars:
    nginx_pgp_url: http://nginx.org/keys/nginx_signing.key
    nginx_repository_url: http://nginx.org/packages/ubuntu/
  tasks:
  - name: Add official nginx PGP key
    apt_key: url={{nginx_pgp_url}} state=present
  - name: Add official nginx repository
    lineinfile : >
      dest=/etc/apt/sources.list
      line='{{item}} {{nginx_repository_url}} {{ansible_distribution_release}} nginx'
    with_items:
      - deb
      - deb-src
  - name: Apt install Nginx
    apt:  pkg=nginx state=present force=yes update_cache=yes
  - name: restart nginx
    service: name=nginx state=restarted
