---
- hosts: dpub_front
  user: da-dev
  sudo: yes
  tasks:
  - name: add-apt-repository ppa:ondrej/php
    command: "add-apt-repository ppa:ondrej/php"
  - name: install php7.1-fpm and php7.1-cli
    apt: pkg={{ item }} force=yes update_cache=yes state=latest
    with_items:
      - php7.1-fpm
      - php7.1-cli
  - name: install php7.1-* extensions
    apt: pkg={{ item }} force=yes update_cache=yes state=latest
    with_items:
      - php7.1-common
      - php7.1-mysql
