---
- hosts: dpub_front
  user: da-dev
  sudo: yes
  tasks:
  - file: src=/usr/bin/python2 dest=/usr/bin/python owner=root group=root mode=0755 state=link
  - name: Apt install python-pip
    apt:  pkg=python-pip force=yes update_cache=yes
  - file: src=/usr/bin/python3 dest=/usr/bin/python owner=root group=root mode=0755 state=link
  - name: Apt install libraries
    apt:  pkg={{ item }} force=yes update_cache=yes
    with_items:
      - python-dev
      - libhdf5-dev
      - libffi-dev
      - libffi6
      - build-essential
      - python3-pip
  - name: Pip3 upgrade
    command: "pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.1.0-cp34-cp34m-linux_x86_64.whl"
  - name: Pip3 upgrade
    command: "python3 -m pip install --upgrade pip"
  - name: Pip3 install asn1crypto-0.22.0
    pip: name=asn1crypto version=0.22.0
  - name: Pip3 install awscli-1.11.115
    pip: name=awscli version=1.11.115
  - name: Pip3 install bcrypt-3.1.3
    pip: name=bcrypt version=3.1.3
  - name: Pip3 install botocore-1.5.78
    pip: name=botocore version=1.5.78
  - name: Pip3 install certifi-2017.4.17
    pip: name=certifi version=2017.4.17
  - name: Pip3 install cffi-1.10.0
    pip: name=cffi version=1.10.0
  - name: Pip3 install chardet-2.3.0
    pip: name=chardet version=2.3.0
  - name: Pip3 install colorama-0.3.7
    pip: name=colorama version=0.3.7
  - name: Pip3 install cryptography-1.9
    pip: name=cryptography version=1.9
  - name: Pip3 install Cython-0.25.2
    pip: name=Cython version=0.25.2
  - name: Pip3 install docutils-0.13.1
    pip: name=docutils version=0.13.1
  - name: Pip3 install futures-3.1.1
    pip: name=futures version=3.1.1
  - name: Pip3 install h5py-2.7.0
    pip: name=h5py version=2.7.0
  - name: Pip3 install idna-2.5
    pip: name=idna version=2.5
  - name: Pip3 install jmespath-0.9.3
    pip: name=jmespath version=0.9.3
  - name: Pip3 install msgpack-python-0.4.8
    pip: name=msgpack-python version=0.4.8
  - name: Pip3 install numpy-1.12.1
    pip: name=numpy version=1.12.1
  - name: Pip3 install packaging-16.8
    pip: name=packaging version=16.8
  - name: Pip3 install pandas-0.20.2
    pip: name=pandas version=0.20.2
  - name: Pip3 install pandas-td-0.8.8
    pip: name=pandas-td version=0.8.8
  - name: Pip3 install paramiko-2.2.0
    pip: name=paramiko version=2.2.0
  - name: Pip3 install protobuf-3.3.0
    pip: name=protobuf version=3.3.0
  - name: Pip3 install pyasn1-0.2.3
    pip: name=pyasn1 version=0.2.3
  - name: Pip3 install pycparser-2.17
    pip: name=pycparser version=2.17
  - name: Pip3 install pygobject-3.20.0
    pip: name=pygobject
  - name: Pip3 install PyMySQL-0.7.11
    pip: name=PyMySQL version=0.7.11
  - name: Pip3 install PyNaCl-1.1.2
    pip: name=PyNaCl version=1.1.2
  - name: Pip3 install pyparsing-2.2.0
    pip: name=pyparsing version=2.2.0
  - name: Pip3 install python-apt-1.1.0b1
    pip: name=python-apt
  - name: Pip3 install python-dateutil-2.6.0
    pip: name=python-dateutil version=2.6.0
  - name: Pip3 install pytz-2017.2
    pip: name=pytz version=2017.2
  - name: Pip3 install PyYAML-3.12
    pip: name=PyYAML version=3.12
  - name: Pip3 install requests-2.9.1
    pip: name=requests version=2.9.1
  - name: Pip3 install rsa-3.4.2
    pip: name=rsa version=3.4.2
  - name: Pip3 install s3transfer-0.1.10
    pip: name=s3transfer version=0.1.10
  - name: Pip3 install scipy-0.19.0
    pip: name=scipy version=0.19.0
  - name: Pip3 install scikit-learn-0.18.1
    pip: name=scikit-learn version=0.18.1
  - name: Pip3 install six-1.10.0
    pip: name=six version=1.10.0
  - name: Pip3 install SQLAlchemy-1.1.10
    pip: name=SQLAlchemy version=1.1.10
  - name: Pip3 install ssh-import-id-5.5
    pip: name=ssh-import-id version=5.5
  - name: Pip3 install sshtunnel-0.1.2
    pip: name=sshtunnel version=0.1.2
  - name: Pip3 install td-client-0.9.0
    pip: name=td-client version=0.9.0
  - name: Pip3 install tensorflow-1.1.0
    pip: name=tensorflow version=1.1.0
  - name: Pip3 install Keras-2.0.5
    pip: name=Keras version=2.0.5
  - name: Pip3 install Theano-0.9.0
    pip: name=Theano version=0.9.0
  - name: Pip3 install tzlocal-1.4
    pip: name=tzlocal version=1.4
  - name: Pip3 install urllib3-1.13.1
    pip: name=urllib3 version=1.13.1
  - name: Pip3 install Werkzeug-0.12.2
    pip: name=Werkzeug version=0.12.2

